name: CI on Push

on:
  workflow_dispatch:
  
  push:
    branches: [ main ]
  
defaults:
  run:
    working-directory: COMP3000Project
    
jobs:
  Practice:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what in there
      run: |
        ls
    - name: Show what it's inside
      run: |
        cd ..
        ls
  Android:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android
      run: |
        ls
        cd COMP3000Project
        echo LS COMP3000Project
        
        echo nuget restoring...
        nuget restore
        
        cd COMP3000Project.Android
        ls
        echo LS COMP3000Project.Android
        
        msbuild COMP3000Project.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
  iOS:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: iOS
      run: |
        cd COMP3000Project
        nuget restore
        msbuild COMP3000Project.iOS/Blank.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
