name: Build Xamarin.Android app

on:
  workflow_dispatch:
  
  push:
    branches: [ main ] 

defaults:
  run:
    working-directory: COMP3000Project

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore COMP3000Project.sln

    - name: Build
      run: msbuild COMP3000Project.csproj /t:PackageForAndroid /p:Configuration=Debug
